### ISSUE TITLE
Broken hopper mechanics

### ISSUE THREAD

**Issue by NicklasMatzulla** [LuminolMC/Luminol#140]
### 服务端版本 LuminolMC Version

0bf42dc

### 预期的行为 Expected behavior

In my case, the code listed below should ensure that items are removed from a hopper and added to a custom block. However, the code is not executed, and no error is returned.

### 观测到的实际行为 Observed/Actual behavior

The event InventoryMoveItemEvent is no longer executed or its interactions are discarded, caused by the patch `[luminol-server/minecraft-patches/features/0066-Use-vanilla-hopper-logic-Leaves-Lithium-Sleeping-Blo.patch](https://github.com/LuminolMC/Luminol/blob/0bf42dcc8d6c09fab78d1bdc5335cb38d7a1f5dc/luminol-server/minecraft-patches/features/0066-Use-vanilla-hopper-logic-Leaves-Lithium-Sleeping-Blo.patch#L1725)`.

### 复现步骤 Steps/models to reproduce

```java
    @EventHandler
    public void onInventoryMoveItemEvent(final @NotNull InventoryMoveItemEvent event) {
        final Inventory blockInventory = event.getDestination();
        if (!(blockInventory.getHolder() instanceof CustomBlockInventoryHolder(final @NotNull Block block))) {
            return;
        }
        final CustomBlockMechanic blockMechanic = NexoBlocks.customBlockMechanic(block);
        if (blockMechanic == null || !blockMechanic.getItemID().equals("sell_warehouse_block")) {
            return;
        }
        final InventoryHolder hopperInventoryHolder = event.getSource().getHolder();
        final Inventory hopperInventory = hopperInventoryHolder == null ? null : hopperInventoryHolder.getInventory();
        if (hopperInventory == null) {
            return;
        }
        final PersistentDataContainer blockData = new CustomBlockData(block, plugin);
        String itemType = blockData.get(ITEM_TYPE_NAMESPACED_KEY, PersistentDataType.STRING);
        if (itemType == null) {
            itemType = event.getItem().getType().name();
            blockData.set(ITEM_TYPE_NAMESPACED_KEY, PersistentDataType.STRING, itemType);
        }
        int storedItemCount = blockData.getOrDefault(ITEM_AMOUNT_NAMESPACED_KEY, PersistentDataType.INTEGER, 0);
        for (int i = 0; i < hopperInventory.getSize(); i++) {
            final ItemStack hopperInventoryItemStack = hopperInventory.getItem(i);
            if (hopperInventoryItemStack == null) {
                continue;
            }
            if (!hopperInventoryItemStack.getType().name().equals(itemType) || hopperInventoryItemStack.hasItemMeta()) {
                if (hopperInventoryItemStack.hasItemMeta()) {
                    event.setCancelled(true);
                }
                if (hopperInventoryItemStack.getType() != Material.AIR) {
                    event.setCancelled(true);
                }
                if (storedItemCount == 0) {
                    blockData.remove(ITEM_TYPE_NAMESPACED_KEY);
                }
                continue;
            }
            int maxItemCount = blockData.getOrDefault(ITEM_MAX_AMOUNT_NAMESPACED_KEY, PersistentDataType.INTEGER, 64);
            int itemSpace = maxItemCount - storedItemCount;
            if (itemSpace <= 0) {
                event.setCancelled(true);
                break;
            }
            blockData.set(ITEM_AMOUNT_NAMESPACED_KEY, PersistentDataType.INTEGER, storedItemCount + 1);
            hopperInventoryItemStack.setAmount(hopperInventoryItemStack.getAmount()-1);
            return;
        }
    }
```

### 插件与数据包列表。 Plugin and Datapack List.

[05:34:55 INFO]: ℹ Server Plugins (16):
[05:34:55 INFO]: Paper Plugins (5):
[05:34:55 INFO]:  - LimitCore, LimitSMP, Nexo, NickSystem, ServerSystem
[05:34:55 INFO]: Bukkit Plugins (11):
[05:34:55 INFO]:  - BetterModel, floodgate, GrimAC, Iris, LuckPerms, Plan, ProtocolLib, spark, Terra, voicechat
[05:34:55 INFO]:  WorldEdit

**Comment by MrHua269** [comment]
https://github.com/LuminolMC/Luminol/commit/80270ce7431234169b963943f0850ae4b7215656

**Comment by NicklasMatzulla** [comment]
> [80270ce](https://github.com/LuminolMC/Luminol/commit/80270ce7431234169b963943f0850ae4b7215656)

Hello, unfortunately, the change still does not work. Please find enclosed the code with which you can check the validity yourself.

Best regards

```java
/*
 * Copyright (c) 2025 LimitMedia
 */

package net.playunlimited.limitsmp.economy;

import net.kyori.adventure.text.Component;
import net.playunlimited.limitsmp.util.customblockdata.CustomBlockData;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.inventory.HopperInventorySearchEvent;
import org.bukkit.event.inventory.InventoryMoveItemEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.ItemStack;
import org.bukkit.persistence.PersistentDataContainer;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.Plugin;
import org.jetbrains.annotations.NotNull;

public class NoteBlockStorageListener implements Listener {
    private final Plugin plugin;
    private final NamespacedKey COUNT_KEY;

    public NoteBlockStorageListener(final @NotNull Plugin plugin) {
        this.plugin = plugin;
        this.COUNT_KEY = new NamespacedKey(plugin, "noteblock_item_count");
    }

    @EventHandler
    public void onHopperInventorySearchEvent(final @NotNull HopperInventorySearchEvent event) {
        final Block block = event.getSearchBlock();
        if (block.getType() != Material.NOTE_BLOCK) {
            return;
        }
        event.setInventory(Bukkit.createInventory(new NoteBlockHolder(block), 9));
    }

    @EventHandler
    public void onInventoryMoveItemEvent(final @NotNull InventoryMoveItemEvent event) {
        final Inventory destination = event.getDestination();
        if (!(destination.getHolder() instanceof NoteBlockHolder holder)) {
            return;
        }
        final Block block = holder.block();
        if (block.getType() != Material.NOTE_BLOCK) {
            return;
        }
        final PersistentDataContainer blockData = new CustomBlockData(block, plugin);
        final int current = blockData.getOrDefault(COUNT_KEY, PersistentDataType.INTEGER, 0);
        blockData.set(COUNT_KEY, PersistentDataType.INTEGER, current + 1);
        final Inventory sourceInventory = event.getSource();
        final ItemStack movedItemStack = event.getItem();
        for (int i = 0; i < sourceInventory.getSize(); i++) {
            final ItemStack itemStack = sourceInventory.getItem(i);
            if (itemStack == null || itemStack.getType() != movedItemStack.getType()) {
                continue;
            }
            final int newAmount = itemStack.getAmount() - 1;
            if (newAmount > 0) {
                itemStack.setAmount(newAmount);
            } else {
                sourceInventory.setItem(i, null);
            }
            break;
        }
        event.setCancelled(true);
    }

    @EventHandler
    public void onPlayerInteract(final @NotNull PlayerInteractEvent event) {
        if (event.getAction() != Action.RIGHT_CLICK_BLOCK) {
            return;
        }
        final Block block = event.getClickedBlock();
        if (block == null || block.getType() != Material.NOTE_BLOCK) {
            return;
        }
        final PersistentDataContainer blockData = new CustomBlockData(block, plugin);
        final int count = blockData.getOrDefault(COUNT_KEY, PersistentDataType.INTEGER, 0);
        final Player player = event.getPlayer();
        player.sendMessage(Component.text("Stored amount: " + count));
    }

    private record NoteBlockHolder(@NotNull Block block) implements InventoryHolder {
        
        @Override
        public @NotNull Inventory getInventory() {
            return Bukkit.createInventory(this, 9);
        }
        
    }

}
```

**Comment by MrHua269** [comment]
Fixed in https://github.com/LuminolMC/Luminol/commit/0d625a1f15343d7bec3fd41eb9f277113b079a7c

**Comment by Suisuroru** [comment]
> > can you have a try with [3052083](https://github.com/LuminolMC/Luminol/commit/305208380651f840a4b97d50338cdd3acd2da24b) ? maybe fixed this
> 
> Hello, thank you very much for your help. Now my custom blocks are able to accept items again. However, for some reason, two items are entering the custom block at the same time, and my logic only allows one item to be added to the block. With Folia, only one item is ever removed, not two. Please take this into account in the patch so that the behavior is normal.
> 
> Best regards and thank you for your help!

Fortunately, Upstream - Leaves have already been involved in fixing this issue and it seems to have been resolved. We will introduce this modification shortly.

**Comment by Suisuroru** [comment]
> > can you have a try with [3052083](https://github.com/LuminolMC/Luminol/commit/305208380651f840a4b97d50338cdd3acd2da24b) ? maybe fixed this
> 
> Hello, thank you very much for your help. Now my custom blocks are able to accept items again. However, for some reason, two items are entering the custom block at the same time, and my logic only allows one item to be added to the block. With Folia, only one item is ever removed, not two. Please take this into account in the patch so that the behavior is normal.
> 
> Best regards and thank you for your help!

fixed in ab525054c73906ef8120333387b1602dd3376229 , we update code from Leaves,they have fixed it

**Comment by NicklasMatzulla** [comment]
> > > can you have a try with [3052083](https://github.com/LuminolMC/Luminol/commit/305208380651f840a4b97d50338cdd3acd2da24b) ? maybe fixed this
> > 
> > 
> > Hello, thank you very much for your help. Now my custom blocks are able to accept items again. However, for some reason, two items are entering the custom block at the same time, and my logic only allows one item to be added to the block. With Folia, only one item is ever removed, not two. Please take this into account in the patch so that the behavior is normal.
> > Best regards and thank you for your help!
> 
> fixed in [ab52505](https://github.com/LuminolMC/Luminol/commit/ab525054c73906ef8120333387b1602dd3376229), we update code from Leaves, they have fixed it

Hello, unfortunately, this has not yet solved the problem. Two items go from the funnel into the custom block, but only one is output. I have marked my full code below. I would be grateful if you could take a look at it. Everything works normally with Folia.

```java
    @EventHandler
    public void onHopperInventorySearchEvent(final @NotNull HopperInventorySearchEvent event) {
        final Block block = event.getSearchBlock();
        final CustomBlockMechanic blockMechanic = NexoBlocks.customBlockMechanic(block);
        if (blockMechanic == null || !blockMechanic.getItemID().equals("sell_warehouse_block")) {
            return;
        }
        event.setInventory(Bukkit.createInventory(new CustomBlockInventoryHolder(block), 9));
    }

    @EventHandler
    public void onInventoryMoveItemEvent(final @NotNull InventoryMoveItemEvent event) {
        final Inventory blockInventory = event.getDestination();
        if (!(blockInventory.getHolder() instanceof CustomBlockInventoryHolder(final @NotNull Block block))) {
            return;
        }
        final CustomBlockMechanic blockMechanic = NexoBlocks.customBlockMechanic(block);
        if (blockMechanic == null || !blockMechanic.getItemID().equals("sell_warehouse_block")) {
            return;
        }
        final InventoryHolder hopperInventoryHolder = event.getSource().getHolder();
        final Inventory hopperInventory = hopperInventoryHolder == null ? null : hopperInventoryHolder.getInventory();
        if (hopperInventory == null) {
            return;
        }
        final PersistentDataContainer blockData = new CustomBlockData(block, plugin);
        String itemType = blockData.get(ITEM_TYPE_NAMESPACED_KEY, PersistentDataType.STRING);
        if (itemType == null) {
            itemType = event.getItem().getType().name();
            blockData.set(ITEM_TYPE_NAMESPACED_KEY, PersistentDataType.STRING, itemType);
        }
        int storedItemCount = blockData.getOrDefault(ITEM_AMOUNT_NAMESPACED_KEY, PersistentDataType.INTEGER, 0);
        for (int i = 0; i < hopperInventory.getSize(); i++) {
            final ItemStack hopperInventoryItemStack = hopperInventory.getItem(i);
            if (hopperInventoryItemStack == null) {
                continue;
            }
            if (!hopperInventoryItemStack.getType().name().equals(itemType) || hopperInventoryItemStack.hasItemMeta()) {
                if (hopperInventoryItemStack.hasItemMeta()) {
                    event.setCancelled(true);
                }
                if (hopperInventoryItemStack.getType() != Material.AIR) {
                    event.setCancelled(true);
                }
                if (storedItemCount == 0) {
                    blockData.remove(ITEM_TYPE_NAMESPACED_KEY);
                }
                continue;
            }
            int maxItemCount = blockData.getOrDefault(ITEM_MAX_AMOUNT_NAMESPACED_KEY, PersistentDataType.INTEGER, 64);
            int itemSpace = maxItemCount - storedItemCount;
            if (itemSpace <= 0) {
                event.setCancelled(true);
                break;
            }
            blockData.set(ITEM_AMOUNT_NAMESPACED_KEY, PersistentDataType.INTEGER, storedItemCount + 1);
            hopperInventoryItemStack.setAmount(hopperInventoryItemStack.getAmount()-1);
            return;
        }
    }

public record CustomBlockInventoryHolder(@NotNull Block block) implements InventoryHolder {
    private static final ConcurrentHashMap<Block, Inventory> CUSTOM_BLOCK_INVENTORIES = new ConcurrentHashMap<>();

    @Override
    public @NotNull Inventory getInventory() {
        return CUSTOM_BLOCK_INVENTORIES.computeIfAbsent(block, key -> Bukkit.createInventory(this, 9));
    }

}

```

**Comment by Bacteriawa** [comment]
> > > > 你能试试[3052083](https://github.com/LuminolMC/Luminol/commit/305208380651f840a4b97d50338cdd3acd2da24b)吗？也许可以解决这个问题
> > > 
> > > 
> > > 您好，非常感谢您的帮助。现在我的自定义块可以再次接受项目了。但是，由于某种原因，两个项目同时进入自定义块，而我的逻辑只允许将一个项目添加到块中。使用 Folia，只删除一个项目，而不是两个。请在补丁中考虑到这一点，以便行为正常。最好的问候，感谢您的帮助！
> > 
> > 
> > 在 [ab52505](https://github.com/LuminolMC/Luminol/commit/ab525054c73906ef8120333387b1602dd3376229) 中修复，我们从 Leaves 更新代码，他们已经修复了它
> 
> 您好，很遗憾，这还没有解决问题。两个项目从漏斗进入自定义块，但只输出一个。我在下面标记了我的完整代码。如果您能看看它，我将不胜感激。Folia 一切正常。
> 
>     @EventHandler
>     public void onHopperInventorySearchEvent(final @NotNull HopperInventorySearchEvent event) {
>         final Block block = event.getSearchBlock();
>         final CustomBlockMechanic blockMechanic = NexoBlocks.customBlockMechanic(block);
>         if (blockMechanic == null || !blockMechanic.getItemID().equals("sell_warehouse_block")) {
>             return;
>         }
>         event.setInventory(Bukkit.createInventory(new CustomBlockInventoryHolder(block), 9));
>     }
> 
>     @EventHandler
>     public void onInventoryMoveItemEvent(final @NotNull InventoryMoveItemEvent event) {
>         final Inventory blockInventory = event.getDestination();
>         if (!(blockInventory.getHolder() instanceof CustomBlockInventoryHolder(final @NotNull Block block))) {
>             return;
>         }
>         final CustomBlockMechanic blockMechanic = NexoBlocks.customBlockMechanic(block);
>         if (blockMechanic == null || !blockMechanic.getItemID().equals("sell_warehouse_block")) {
>             return;
>         }
>         final InventoryHolder hopperInventoryHolder = event.getSource().getHolder();
>         final Inventory hopperInventory = hopperInventoryHolder == null ? null : hopperInventoryHolder.getInventory();
>         if (hopperInventory == null) {
>             return;
>         }
>         final PersistentDataContainer blockData = new CustomBlockData(block, plugin);
>         String itemType = blockData.get(ITEM_TYPE_NAMESPACED_KEY, PersistentDataType.STRING);
>         if (itemType == null) {
>             itemType = event.getItem().getType().name();
>             blockData.set(ITEM_TYPE_NAMESPACED_KEY, PersistentDataType.STRING, itemType);
>         }
>         int storedItemCount = blockData.getOrDefault(ITEM_AMOUNT_NAMESPACED_KEY, PersistentDataType.INTEGER, 0);
>         for (int i = 0; i < hopperInventory.getSize(); i++) {
>             final ItemStack hopperInventoryItemStack = hopperInventory.getItem(i);
>             if (hopperInventoryItemStack == null) {
>                 continue;
>             }
>             if (!hopperInventoryItemStack.getType().name().equals(itemType) || hopperInventoryItemStack.hasItemMeta()) {
>                 if (hopperInventoryItemStack.hasItemMeta()) {
>                     event.setCancelled(true);
>                 }
>                 if (hopperInventoryItemStack.getType() != Material.AIR) {
>                     event.setCancelled(true);
>                 }
>                 if (storedItemCount == 0) {
>                     blockData.remove(ITEM_TYPE_NAMESPACED_KEY);
>                 }
>                 continue;
>             }
>             int maxItemCount = blockData.getOrDefault(ITEM_MAX_AMOUNT_NAMESPACED_KEY, PersistentDataType.INTEGER, 64);
>             int itemSpace = maxItemCount - storedItemCount;
>             if (itemSpace <= 0) {
>                 event.setCancelled(true);
>                 break;
>             }
>             blockData.set(ITEM_AMOUNT_NAMESPACED_KEY, PersistentDataType.INTEGER, storedItemCount + 1);
>             hopperInventoryItemStack.setAmount(hopperInventoryItemStack.getAmount()-1);
>             return;
>         }
>     }
> 
> public record CustomBlockInventoryHolder(@NotNull Block block) implements InventoryHolder {
>     private static final ConcurrentHashMap<Block, Inventory> CUSTOM_BLOCK_INVENTORIES = new ConcurrentHashMap<>();
> 
>     @Override
>     public @NotNull Inventory getInventory() {
>         return CUSTOM_BLOCK_INVENTORIES.computeIfAbsent(block, key -> Bukkit.createInventory(this, 9));
>     }
> 
> }

`blockData.set(ITEM_AMOUNT_NAMESPACED_KEY, PersistentDataType.INTEGER, storedItemCount + 1);
hopperInventoryItemStack.setAmount(hopperInventoryItemStack.getAmount()-1);
return; // This is where the problem lies.
`

**Comment by Bacteriawa** [comment]
Instead of returning directly, it continues processing other items.
The event is canceled only after the item has been processed.

**Comment by NicklasMatzulla** [comment]
Hello,

I have now manually resolved the issue in my plugin, so you no longer need to worry about it. However, thank you for your help, I really appreciate the support!

Best regards

**Comment by MrHua269** [comment]
&gt; 您好，
&gt; 
&gt; 我已在插件中手动解决了该问题，您无需再为此担忧。但仍要感谢您的帮助，您的支持令我深表感激！
&gt; 
&gt; 此致

抱歉回复迟了。在执行https://github.com/LuminolMC/Luminol/commit/d254f11495609ee38746064e47dea5c9f3f7dc2bnow()后已修复。
